### ISSUE TITLE
Large image on frontpage

### ISSUE THREAD

**Issue by timharek** [SindreKjelsrud/sindrekjelsrud.github.io#2]
Cool website! 🙌 

I noticed on the frontpage that your avatar is over 8 MB. And it loads twice for some reason. Making your frontpage 17.33 MB 😅

You may be able to reduce the size of your avatar down to 9 kB.

And since you use Hugo I see that they offer [image processing](https://gohugo.io/content-management/image-processing/) which may help automate the reduction when the site is generated. I haven't really tried Hugo myself so I'm not too familiar with it.

**Comment by SindreKjelsrud** [comment]
Thank you for the issue!! Will take a look at it when I've got time for it🫶
